server.port=8080
spring.application.name=gateway-service

service.iam.url=http://localhost:8081
service.catalogue.url=http://localhost:8082
service.auction.url=http://localhost:8083
service.payment.url=http://localhost:8084
