server:
  port: 8082

spring:
  application:
    name: catalogue-service
    
  cloud:
    gateway:
      routes:
        - id: catalogue-service
          uri: http://localhost:8082
          predicates:
            - Path=/items/**

  datasource:
    url: jdbc:postgresql://localhost:5434/cataloguedb
    username: catalogue
    password: catalogue
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG