MERGE INTO items (id, name, description, category, starting_price, seller_id,
    auction_start_time, auction_end_time, status,
    shipping_days, shipping_cost, expedited_shipping_cost)
KEY(id)
VALUES
    (1, 'Vintage Watch', 'A classic 1970s Swiss watch in excellent condition.',
     'Accessories', 50.00, 1,
     CURRENT_TIMESTAMP, DATEADD('HOUR', 48, CURRENT_TIMESTAMP),
     'ACTIVE', 7, 10.00, 25.00),
    (2, 'Gaming Laptop', 'High performance gaming laptop, 32GB RAM, RTX 4080.',
     'Electronics', 800.00, 1,
     CURRENT_TIMESTAMP, DATEADD('HOUR', 72, CURRENT_TIMESTAMP),
     'ACTIVE', 5, 15.00, 35.00),
    (3, 'Antique Vase', 'Ming Dynasty replica vase, hand-painted.',
     'Antiques', 100.00, 2,
     CURRENT_TIMESTAMP, DATEADD('HOUR', 24, CURRENT_TIMESTAMP),
     'ACTIVE', 10, 20.00, 40.00),
    (4, 'Mountain Bike', 'Trek mountain bike, lightly used, 21-speed.',
     'Sports', 200.00, 2,
     CURRENT_TIMESTAMP, DATEADD('HOUR', 36, CURRENT_TIMESTAMP),
     'ACTIVE', 14, 30.00, 60.00),
    (5, 'Leather Sofa', 'Brown leather 3-seater sofa, excellent condition.',
     'Furniture', 300.00, 1,
     CURRENT_TIMESTAMP, DATEADD('HOUR', 96, CURRENT_TIMESTAMP),
     'ACTIVE', 10, 50.00, 90.00);